apiVersion: v1 
kind: Service
metadata:
  name: nginx 
spec:
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx