apiVersion: v1 
kind: Service
metadata:
  name: nginx-np 
spec:
  type: NodePort
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    demo: np
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np 
  labels:
    project: expense
    component: backend
    environment: dev
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx